replicaCount: 1

image:
  repository: cnmeow/vnplaterec-backend
  tag: "1748848822"
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 2106

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
