replicaCount: 1

image:
  repository: cnmeow/vnplaterec-backend
  tag: "1748857303"
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 2106

livenessProbe:
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10
